version: '3.8'

services:
  node_app:
    container_name: node_app
    build: .
    image: avasoft/node_app
    ports:
      - "3000:3000"
    environment:
      - MYSQL_DB=avasoft_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql_db
    depends_on:
      - mysql_db
    restart: always
  mysql_db:
    container_name: mysql_db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=avasoft_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql 
volumes:
  mysql_data: {}
    